[project]
name = "lotionai-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "langchain>=0.0.27",
    "langgraph>=0.2.62",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
]
